[package]
name = "spike-schema-ts"
version = "0.0.0"
edition.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { workspace = true }
serde-wasm-bindgen = { workspace = true }
wasm-bindgen = { workspace = true }
probe-rs-rpc = { git = "https://github.com/beriberikix/probe-rs", branch = "wasm-rpc-client" }
postcard-rpc = { version = "0.12", features = ["use-std"] }
postcard-schema = { version = "0.2", features = ["use-std", "derive"] }
