#!/usr/bin/env python3
"""Generate packages/client/src/registers.ts from probe-rs's register tables.

probe-rs's RPC has no register-list endpoint: `core/read_registers` and
`core/write_reg` take probe-rs `RegisterId`s, so the client needs the same
tables probe-rs uses (probe-rs/src/architecture/**/registers*.rs). Usage:

    scripts/gen-registers.py <probe-rs master checkout>
"""
import re, sys, pathlib

root = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "../prs-master") / "probe-rs/src/architecture"
SOURCES = {
    # group key: (file, set names to take in order; None = every CoreRegister literal in the file)
    "armCommon": ("arm/core/registers/cortex_m.rs", ["ARM32_COMMON_REGS_SET", "PC", "FP", "SP", "RA"]),
    "cortexM": ("arm/core/registers/cortex_m.rs", ["CORTEX_M_COMMON_REGS_SET", "XPSR"]),
    "cortexMFp": ("arm/core/registers/cortex_m.rs", ["CORTEX_M_WITH_FP_REGS_SET"]),
    "v8mMain": ("arm/core/registers/armv8m.rs", ["V8M_MAIN_REGS_SET"]),
    "v8mSecurity": ("arm/core/registers/armv8m.rs", ["V8M_SECURITY_REGS_SET"]),
    "riscv": ("riscv/registers.rs", None),
    "xtensa": ("xtensa/registers.rs", None),
}

skipped = []
LIT = re.compile(r"CoreRegister\s*\{(.*?)unwind_rule[^}]*\}", re.S)

def parse_literals(text):
    out = []
    for m in LIT.finditer(text):
        body = m.group(1)
        name = re.search(r'RegisterRole::Core\("([^"]+)"\)', body)
        rid = re.search(r"RegisterId\(([^)]+)\)", body)
        dt = re.search(r"RegisterDataType::(UnsignedInteger|FloatingPoint)\((\d+)\)", body)
        if not (name and rid and dt):
            continue
        roles = re.findall(r"RegisterRole::(\w+)", body)
        try:
            rid_value = int(rid.group(1).replace("_", ""), 0)
        except ValueError:
            # e.g. Xtensa's `0x0300 | UserRegister::Fcr as u16`: not needed for debugging views yet.
            skipped.append(name.group(1))
            continue
        out.append({
            "name": name.group(1),
            "id": rid_value,
            "bits": int(dt.group(2)),
            "float": dt.group(1) == "FloatingPoint",
            "roles": [r for r in roles if r != "Core"],
        })
    return out

def block(text, name):
    """Source text of `static NAME ... = ...;` or `const NAME: CoreRegister = ...;`."""
    m = re.search(rf"(?:static|const)\s+{name}\b[^=]*=", text)
    if not m:
        raise SystemExit(f"{name} not found")
    depth, i = 0, m.end()
    while True:
        c = text[i]
        if c in "[{(":
            depth += 1
        elif c in "]})":
            depth -= 1
        elif c == ";" and depth == 0:
            return text[m.end():i]
        i += 1

groups = {}
for key, (file, names) in SOURCES.items():
    text = (root / file).read_text()
    regs = parse_literals(text) if names is None else [r for n in names for r in parse_literals(block(text, n))]
    seen, uniq = set(), []
    for r in regs:
        if r["id"] not in seen:
            seen.add(r["id"])
            uniq.append(r)
    groups[key] = sorted(uniq, key=lambda r: r["id"]) if key == "armCommon" else uniq

lines = [
    "// Generated by scripts/gen-registers.py from probe-rs's register tables. Do not edit.",
    "// probe-rs RPC identifies registers by probe-rs RegisterId; these tables give names and widths.",
    "",
    "export interface RegisterInfo {",
    "  /** probe-rs RegisterId */",
    "  id: number;",
    "  name: string;",
    "  bits: number;",
    "  float: boolean;",
    "  /** probe-rs RegisterRole names besides Core, e.g. ProgramCounter, StackPointer, FloatingPoint */",
    "  roles: string[];",
    "}",
    "",
]
for key, regs in groups.items():
    lines.append(f"export const {key}: RegisterInfo[] = [")
    for r in regs:
        roles = ", ".join(f"'{x}'" for x in r["roles"])
        lines.append(f"  {{ id: {r['id']}, name: '{r['name']}', bits: {r['bits']}, float: {str(r['float']).lower()}, roles: [{roles}] }},")
    lines.append("];")
    lines.append("")
out = pathlib.Path(__file__).resolve().parent.parent / "packages/client/src/registers.generated.ts"
out.write_text("\n".join(lines))
print(f"skipped (non-literal ids): {skipped}")
print(f"wrote {out}: " + ", ".join(f"{k}={len(v)}" for k, v in groups.items()))
